### ISSUE TITLE
Coldbox applications...

### ISSUE THREAD

**Issue by Daemach** [pixl8/socket.io-lucee#7]
I've tried integrating this module with coldbox, but it's not working correctly as of step 2 of the tutorial.  When I restart the server I get the following error:  Failed to bind to kubernetes.docker.internal/127.0.0.1:3000  the k8/docker thing is kind of odd...

It would be great if you could integrate this more completely with coldbox - module settings to choose the port binding would be great, a logbox appender for async messaging, etc.   I use pusher.com at the moment but would love to move to this module instead!

![image](https://user-images.githubusercontent.com/12553953/101258208-da19f400-36d5-11eb-8ea9-301f6245dc23.png)

**Comment by Daemach** [comment]
You could look at https://github.com/coldbox-modules/sentry for inspiration for the logbox appender.

https://coldbox.ortusbooks.com/hmvc/modules

https://blog.mattclemente.com/2018/05/23/from-forgebox-package-to-coldbox-module.html

**Comment by DominicWatson** [comment]
I've started on a Preside module for this - and potentially could do a standalone Coldbox one also. However, I'm not going to have the time to create and maintain a project that I'm not actively using.  It would certainly be a separate project that had a dependency on this one and happy to offer any guidenace in setting one up.
